Categories:
  - Internet
  - Multimedia
License: MIT
AuthorName: DigitallyRefined
SourceCode: https://github.com/DigitallyRefined/android-ip-camera
IssueTracker: https://github.com/DigitallyRefined/android-ip-camera/issues
Liberapay: DigitallyRefined

AutoName: Android IP Camera

RepoType: git
Repo: https://github.com/DigitallyRefined/android-ip-camera.git

Builds:
  - versionName: 0.3.1
    versionCode: 31
    commit: bc65e7e9837ecdc3e056d6b4e9de60e57be91d12
    subdir: app
    gradle:
      - yes
    gradleprops:
      - skipSigning=true
      - enableAbiSplits=false

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 0.3.1
CurrentVersionCode: 31
